import math


MAX_NODES = math.pow(2,20)

c1=1;
c2=1;
c3=1;
cp=4;


WEIGHT_SHIFT_STRENGTH = 0.3;
WEIGHT_RANDOM_STRENGTH = 1;

SURVIVORS= 0.8;

PROBABILITY_MUTATE_LINK = 0.01;
PROBABILITY_MUTATE_NODE = 0.05;
PROBABILITY_MUTATE_WEIGHT_SHIFT = 0.02;
PROBABILITY_MUTATE_WEIGHT_RANDOM= 0.02;
PROBABILITY_MUTATE_TOGGLE_LINK = 0.01;

MUTATION_LINK_ATTEMPS=100
